### ISSUE TITLE
Linux Version?

### ISSUE THREAD

**Issue by vincentlarkin** [MarioMasta64/EverythingPortable#2]
Hello, you did not have an email attached to your GitHub so I will contact you this way. I was wondering if I could make a GNU/Linux version of this concept, perhaps take some of your source code? You would be credited.

**Comment by MarioMasta64** [comment]
loveme0198@gmail.com & i dont much know much about the *nix enviroment. i mostly only know about the win32 shell and such

**Comment by MarioMasta64** [comment]
if i ever learn the *nix enviroment i may consider it. till then its win32 shell only ( batch and vbs :D )

**Comment by MarioMasta64** [comment]
oh sorry seems i misread. but yknow all i do is just automate the process of manually installing something right? theres nothing to credit other than the idea. since linux and windows use different code basically everything that was my code would be changed. after all batch scripts dont run on linux (less its wine). i have no clue how to go about making things portable on linux outside wine (since windows) but i know for sure none of my code would actually be included. so if youre inspired by my project feel free to link it. but your project would be yours as far as i hear.

**Comment by MarioMasta64** [comment]
https://github.com/MarioMasta64/EverythingPortable-Linux/

i gave it a try and well, i hate this  feel free to try it out yourself.
