### ISSUE TITLE
No longer works.

### ISSUE THREAD

**Issue by COTYWALT** [MarioMasta64/EverythingPortable#23]
Steam fails to install.

**Comment by MarioMasta64** [comment]
this provides no info
but
should be fixed update launcher then try again i did some changes to fix lessmsi downloading and extracting

**Comment by MarioMasta64** [comment]
also please keep in mind the readme "cons: its very likely to break since its a script and this is mostly only a hobby project i do to familiarize myself with different programs and how to make them portable and is a very amateur project that may work but is held together by bandages and shouldnt be taken seriously but if you find any of it helpful then thats nice"
