### ISSUE TITLE
steam not working

### ISSUE THREAD

**Issue by mrbrightside731** [MarioMasta64/EverythingPortable#24]
when I try to install steam, it says I need to download the latest version but that also seems to do nothing. May you fix it? Thank You

**Comment by psysxet** [comment]
I have the same problem. 
the recommended action point "D" (check for updates) does nothing. So does Option 1 "reinstall steam".

**Comment by MarioMasta64** [comment]
should be fixed update launcher then try again i did some changes to fix lessmsi downloading and extracting

**Comment by MarioMasta64** [comment]
also please keep in mind the readme "cons: its very likely to break since its a script and this is mostly only a hobby project i do to familiarize myself with different programs and how to make them portable and is a very amateur project that may work but is held together by bandages and shouldnt be taken seriously but if you find any of it helpful then thats nice"
