### ISSUE TITLE
2 addtion to launch_epic_games.bat

### ISSUE THREAD

**Issue by Cleasonsook** [MarioMasta64/EverythingPortable#26]
Hi 
I have slow / bad internet 
with all the images that have to be downloaded and animations 
can't view a lot of what I should be able to see

one of the big parts is to know what program is being downloaded

it would be nice if the launcher ask me 
but it dose not it just starts and I am stuck wondering ..

I need a menu to let me know what it is downloading 
and to either pause it or stop it 
with the option to resuming the file 
so I can use other parts of the main program 

I would be nice to view download progress but the pausing the download 
and stopping it if I want to would be the top of my list of needed things

Thank you

**Comment by MarioMasta64** [comment]
when downloading it says whats being downloaded 
![image](https://user-images.githubusercontent.com/20806802/227709522-74d14225-f93d-4420-a04a-c3acecad3c49.png)

things are executed one after another and pausing the download isnt possible since its an ordered list of things to do, you can press ctrl+c and say no to skip but most sections will try to loop to make sure whatever it is is downloaded

i believe you would want more than what my hobby project is capable of i would suggest something like portableapps or portapps
