### ISSUE TITLE
Genshin Impact/ZZZ portable?.. (and some other stuff like questions)

### ISSUE THREAD

**Issue by c1bles** [MarioMasta64/EverythingPortable#40]
Hey! Sorry to bother, but would it be able to make Genshin, ZZZ, or gamemaker portable ? (for gamemaker even the LTS version is fine).

And for minecraft legacy and minecraft, how does it work ? Is minecraft legacy an old version, and are they cracked ?

Oh yea, and finally Authy has ceased support for pc, so the portable version isn't needed anymore.

Thank you!

**Comment by MarioMasta64** [comment]
> Hey! Sorry to bother, but would it be able to make Genshin, ZZZ, or gamemaker portable ? (for gamemaker even the LTS version is fine).

requires anticheat, requires anticheat, if you mean gamemaker 1 instead of gamemaker 2 i dont see a reason if you mean gamemaker 2 its already done check repo

> 
> And for minecraft legacy and minecraft, how does it work ? Is minecraft legacy an old version, and are they cracked ?

its just normal minecraft with a portable java you still require an account as far as im aware minecraft legacy no longer works its just the old java launcher versus the new launcher you would get if you download from the site / microsoft store

> 
> Oh yea, and finally Authy has ceased support for pc, so the portable version isn't needed anymore.
> 

this is already stated in #14 please read issues first before anything

> Thank you!
