### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by EPICNESS2008** [MarioMasta64/EverythingPortable#41]
Does this only run Steam or does it run other stuff?

**Comment by SourceCoat** [comment]
Are you asking if if runs steam games or are you asking if it makes other apps portable?

I don't think it runs other apps but it can let you run steam games, I'm not the creator so I could be wrong

**Comment by ve-cto** [comment]
Steam games from my personal experience work well. There are some games that require extra materials like shaders that you have to download and configure separately so that they are portable, but for most games it's fine.

If you download `launch_everything.bat`, you can see a list of apps that are supported by everythingportable, which you can then download the specific launcher for. Everythingportable does not make any app portable, only those that are listed in `launch_everything.bat`.

Once you download an app-specific launcher, if required, it gives you instructions on how to set it up. Some launchers require additional materials, like an installer.

You can see the list of functioning launchers in #14.

**Comment by MarioMasta64** [comment]
> Does this only run Steam or does it run other stuff?

given how people treat the project thats pretty much how it might as well be people pretty much only care about it for steam (its also part of the reason aside from stress being burnt out and not finding doing this stuff as fun or needed anymore that i dont maintain anything aside basically the steam launcher anymore)

all of the files are in the same repo it says "everything portable" the download page has the launch everything this is not a steam repo its a repo for everything i do so its all together

you can either get launch_*appname*.bat for a standalone for a specific launcher or the download from the releases page which is launch_everything.bat

**Comment by MarioMasta64** [comment]
> Steam games from my personal experience work well. There are some games that require extra materials like shaders that you have to download and configure separately so that they are portable, but for most games it's fine.
> 
> If you download `launch_everything.bat`, you can see a list of apps that are supported by everythingportable, which you can then download the specific launcher for. Everythingportable does not make any app portable, only those that are listed in `launch_everything.bat`.
> 
> Once you download an app-specific launcher, if required, it gives you instructions on how to set it up. Some launchers require additional materials, like an installer.
> 
> You can see the list of functioning launchers in #14.

good explanation
